config/routes.rb
Rails.application.routes.draw do
  root to: 'personal_data#index'
  resources :personal_data
  resources :employments, only: [:create] do
    member do
      post :add_employment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employment.rb
class Employment < ApplicationRecord
  belongs_to :personal_data

  validates :employer, presence: true
  validates :date_started, presence: true
  validates :date_ended, presence: true
end

app/models/personal_data.rb
class PersonalData < ApplicationRecord
  has_many :employments, dependent: :destroy

  validates :first_name, presence: true, length: { maximum: 25 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # respond_to :html, :json
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  def create
    @personal_data = PersonalData.find_by(id: employment_params[:personal_data_id])
    employment_params[:employer].each_with_index do |emp, index|
      @employment = Employment.new(employer: emp, date_started: employment_params[:date_started][index], date_ended: employment_params[:date_ended][index])
      @employment.personal_data_id = @personal_data.id
      @employment.save
    end

    flash[:notice] = "Personal and Employment data is added successfully."
    respond_to do |format|
      format.html { redirect_to personal_data_path }
    end
  end

  def add_employment
    helpers.fields model: Employment.new do |form|
      render turbo_stream: turbo_stream.append(
        'add-employment',
        partial: 'employments/employment_data_fields',
        locals: { form: form, first_employment: nil }
      )
    end
  end

  private

  def employment_params
    params.require(:employment).permit(:personal_data_id, employer: [], date_started: [], date_ended: [])
  end
end

app/controllers/personal_data_controller.rb
class PersonalDataController < ApplicationController
  def index
  end

  def create
    @personal_data = PersonalData.new(personal_data_params)

    respond_to do |format|
      if @personal_data.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.remove('personal-data-form') +
                                turbo_stream.update(
                                  'employment-modal',
                                  partial: 'employments/employment_modal',
                                  locals: { personal_data_id: @personal_data.id }
                                )

        end
      else
        flash[:alert] = "The record is already present in the database. Please provide new details."
        format.html { redirect_to new_personal_datum_path }
      end
    end

  end

  def new
    @personal_data = PersonalData.new
  end

  private

  def personal_data_params
    params.require(:personal_data).permit(:first_name, :last_name, :nickname, :email, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/helpers/personal_data_helper.rb
module PersonalDataHelper
end

app/views/employments/_employment_data_fields.html.slim
- border_style = first_employment ? "none" : "1px solid grey"
- custom_label_classes = 'mb-1 text-md font-bold text-gray-700'
- custom_text_date_field_classes = 'px-3 py-2 border rounded-lg'

hr.mb-10(style="border-width: 1px; border-style: #{border_style}; border-color: grey;")

.my-2
  .flex.flex-col
    = form.label 'Employer', class: custom_label_classes
    = form.text_field :employer, autocomplete: "off", required: true, name: 'employment[employer][]', id: "employerName", class: custom_text_date_field_classes, data: { controller: 'employments' }
.my-5
  .flex.flex-col
    = form.label 'Date Started', class: custom_label_classes
    = form.date_field :date_started, autocomplete: "off", required: true, name: 'employment[date_started][]', class: custom_text_date_field_classes, data: { controller: 'employments' }
.my-5
  .flex.flex-col
    = form.label 'Date Employment Ended', class: custom_label_classes
    = form.date_field :date_ended, autocomplete: "off", required: true, name: 'employment[date_ended][]', class: custom_text_date_field_classes, data: { controller: 'employments' }

app/views/employments/_employment_form.html.slim
= form_with(model: employment, url: employments_path, data: { turbo_frame: "_top" } ) do |form|
  = form.hidden_field :personal_data_id, value: personal_data_id
  =render 'employments/employment_data_fields', form: form, first_employment: :true
  #add-employment
  .inline
    = link_to 'Add Employment', add_employment_employment_path(personal_data_id), class: 'rounded-lg py-3 px-5 bg-green-600 text-white inline-block font-medium cursor-pointer', data: { turbo_method: :post }
    = form.submit 'Save', id: 'saveButton', class: 'rounded-lg py-3 px-5 bg-green-600 text-white inline-block font-medium cursor-pointer ml-2'

app/views/employments/_employment_modal.html.slim
.fixed.inset-0.flex.items-center.justify-center.z-50.bg-black.bg-opacity-50
  .modal-wrapper.bg-white.p-20.rounded-md
    h1.text-gray-800.font-semibold.text-xl.mb-4.text-center Employment Data
    = render 'employments/employment_form', employment: Employment.new, personal_data_id: personal_data_id

app/views/layouts/application.html.slim
doctype html
html
  head
    title EmployeeDataManagement
    meta(name='viewport' content='width=device-width, initial-scale=1')
    == csrf_meta_tags
    == csp_meta_tag
    == stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    == stylesheet_link_tag "application", "data-turbo-track": "reload"
    == stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css'
    == javascript_importmap_tags

  body
    main.container.mx-auto.mt-28.px-5.flex
      == turbo_frame_tag "modal"
      == turbo_frame_tag "employment-modal"
      == yield

app/views/personal_data/_personal_data_form.html.slim
= turbo_frame_tag 'personal-data-form' do
  - if flash[:alert].present?
  .alert.alert-warning.text-yellow-500= flash[:alert]
  = form_with model: @personal_data, url: personal_data_path, method: :post, data: { controller: 'personal-data' } do |form|
    - custom_label_classes = 'mb-1 text-md font-bold text-gray-700'
    - custom_text_field_classes = 'px-3 py-2 border rounded-lg'
    .form-group.mb-4
      .flex.flex-col
        = form.label :first_name, class: custom_label_classes do
          | First Name
          span.text-red-500.required *
        = form.text_field :first_name, class: custom_text_field_classes, required: true, maxlength: 25, data: { action: 'input->personal-data#validateCharacters', personal_data_target: 'firstNameInput' }

    .form-group.mb-4
      .flex.flex-col
        = form.label :last_name, class: custom_label_classes do
          | Last Name
          span.text-red-500.required *
        = form.text_field :last_name, class: custom_text_field_classes, required: true, maxlength: 50, data: { action: 'input->personal-data#validateCharacters', personal_data_target: 'lastNameInput' }

    .form-group.mb-4
      .flex.flex-col
        = form.label :nickname, class: custom_label_classes
        = form.text_field :nickname, class: custom_text_field_classes

    .form-group.mb-4
      .flex.flex-col
        = form.label :email, class: custom_label_classes do
          | Email Address
          span.text-red-500.required *
        = form.text_field :email, class: custom_text_field_classes, required: true, data: { personal_data_target: 'email', action: 'blur->personal-data#validateEmail' }
        = content_tag :div, '', class: 'text-red-500 text-sm mt-1', id: 'emailError', data: { personal_data_target: 'emailError' }

    .form-group.mb-4
      .flex.flex-col
        = form.label :phone, class: custom_label_classes do
          | Phone Number
          span.text-red-500.required *
        = form.text_field :phone, class: custom_text_field_classes, required: true, data: { personal_data_target: 'phone', action: 'blur->personal-data#formatPhone' }
        = content_tag :div, '', class: 'text-red-500 text-sm mt-1', id: 'phoneError', data: { personal_data_target: 'phoneError' }

    = form.submit 'Save', id: 'saveButton', class: 'rounded-lg py-3 px-5 bg-green-600 text-white inline-block font-medium cursor-pointer mt-4'
    = button_tag 'Cancel', data: { controller: 'personal-data', action: 'personal-data#cancelForm' }, type: 'button', class: 'rounded-lg py-3 px-5 bg-green-600 text-white inline-block font-medium cursor-pointer ml-2'

app/views/personal_data/index.html.slim
.container.flex.flex-col.justify-center.items-center
  - if flash[:notice].present?
  .alert.alert-success.text-green-500= flash[:notice]
  = link_to 'Personal Data', new_personal_datum_path, method: :get, data: { turbo_frame: "modal" }, class: 'rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium mt-4'

app/views/personal_data/new.html.slim
= turbo_frame_tag 'modal' do
  .fixed.inset-0.flex.items-center.justify-center.z-50.bg-black.bg-opacity-50
    .modal-wrapper.bg-white.p-20.rounded-md
      h1.text-gray-800.font-semibold.text-xl.mb-4.text-center Personal Data
      == render 'personal_data_form'